export const cardMockedData = [
  {
    id: 1,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
  {
    id: 2,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
  {
    id: 3,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
  {
    id: 4,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
  {
    id: 5,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
  {
    id: 6,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
  {
    id: 7,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
  {
    id: 8,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
  {
    id: 9,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
  {
    id: 10,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
  {
    id: 11,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
  {
    id: 12,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
];
