export const cardMockedData = [
  {
    id: 1,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
  {
    id: 2,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
  {
    id: 3,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
  {
    id: 4,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
  {
    id: 5,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
  {
    id: 6,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
  {
    id: 7,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
  {
    id: 8,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
  {
    id: 9,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
  {
    id: 10,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
  {
    id: 11,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
  {
    id: 12,
    tag: 'Novo',
    image: '/assets/produto-mockup.png',
    alt: 'Product Mockup',
    title: 'Lorem ipsum dolor sit amet consectetuer adipiscing elit',
    fullPrice: '100,00',
    priceWithDiscount: '79,90',
    discount: '10',
    installments: '10x R$ 7,99',
  },
];

export const institutionalMockedData = {
  header: 'Institucional',
  body: [
    'Sobre Nós',
    'Nossas Lojas',
    'Privacidade e Segurança',
    'Termos e Condições',
  ],
};

export const helpMockedData = {
  header: 'Central de ajuda',
  body: [
    'Fale Conosco',
    'Frete e Entrega',
    'Trocas e Devoluções',
    'Forma de Pagamento',
    'FAQ',
  ],
};

export const serviceMockedData = {
  header: 'Atendimento',
  body: [
    'Telefone: (00) 1234-5678',
    'E-mail: exemplo@exemplo.com.br',
    'Horário de atendimento:',
  ],
  officeHours: [
    { days: 'Segunda a Sábado', time: '07h00 às 23h00' },
    { days: 'Domingos e Feriados', time: '07h00 às 21h00' },
  ],
};
